export {default as Home} from '../pages/home/Home'
export {default as UserList} from '../pages/userList/UserList'
export {default as User} from '../pages/user/User'
export {default as NewUser} from '../pages/newUser/NewUser'
export {default as ProductList} from '../pages/productList/ProductList'
export {default as Product} from '../pages/product/Product'
export {default as NewProduct} from '../pages/newProduct/NewProduct'